# Generated by Django 6.0.3 on 2026-06-22 15:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.AddField(
            model_name='comment',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
